import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const indexCss = readFileSync(new URL('../../index.css', import.meta.url), 'utf8')
const designTokens = readFileSync(new URL('../../design-tokens.css', import.meta.url), 'utf8')
const studioShell = readFileSync(new URL('./StudioShell.jsx', import.meta.url), 'utf8')
const useThemeSource = readFileSync(new URL('../../hooks/useTheme.js', import.meta.url), 'utf8')
const authorChatPanel = readFileSync(new URL('../AuthorChatPanel.jsx', import.meta.url), 'utf8')
const settingsPanel = readFileSync(new URL('../SettingsPanel.jsx', import.meta.url), 'utf8')
const locales = readFileSync(new URL('../../i18n/locales.js', import.meta.url), 'utf8')
const outlineView = readFileSync(new URL('../OutlineView.jsx', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../Sidebar.jsx', import.meta.url), 'utf8')
const chapterWorkbench = readFileSync(new URL('../ChapterWorkbench.jsx', import.meta.url), 'utf8')
const chapterWorkspace = readFileSync(new URL('./ChapterWorkspace.jsx', import.meta.url), 'utf8')
const workspaceTabs = readFileSync(new URL('./WorkspaceTabs.jsx', import.meta.url), 'utf8')
const useEditorSelection = readFileSync(new URL('../workbench/useEditorSelection.js', import.meta.url), 'utf8')
const plotGraphView = readFileSync(new URL('../PlotGraphView.jsx', import.meta.url), 'utf8')
const deepSpaceBackdropUrl = new URL('./DeepSpaceBackdrop.jsx', import.meta.url)
const deepSpaceBackdrop = existsSync(deepSpaceBackdropUrl) ? readFileSync(deepSpaceBackdropUrl, 'utf8') : ''
const atmosphereBackdrop = readFileSync(new URL('./AtmosphereBackdrop.jsx', import.meta.url), 'utf8')
const romanUtilUrl = new URL('../../utils/roman.ts', import.meta.url)
const previewHtml = readFileSync(new URL('../../../../docs/design/creative-flow-preview.html', import.meta.url), 'utf8')
const tauriConfig = readFileSync(new URL('../../../../src-tauri/tauri.conf.json', import.meta.url), 'utf8')

function cssBlock(selector) {
  const start = indexCss.indexOf(`${selector} {`)
  if (start === -1) return ''
  const end = indexCss.indexOf('\n}', start)
  return end === -1 ? indexCss.slice(start) : indexCss.slice(start, end)
}

describe('visual polish direction', () => {
  it('adds frosted shell edges and animated theme ambience', () => {
    expect(indexCss).toContain('ambientDrift')
    expect(indexCss).toContain('starDrift')
    expect(indexCss).toContain('starTwinkle')
    expect(indexCss).toContain('--ambient-star-opacity')
    expect(indexCss).toContain('--ambient-star-twinkle-opacity')
    expect(indexCss).toContain('--glass-shell: color-mix')
    expect(indexCss).toContain('backdrop-filter: blur(42px)')
    expect(indexCss).toContain('box-shadow: var(--glass-edge-shadow)')
    expect(indexCss).toContain('--frost-noise-opacity')
    expect(indexCss).toContain('frostGrain')
    expect(indexCss).toContain('mix-blend-mode: var(--ambient-blend')
    expect(tauriConfig).toContain('"windowEffects"')
    expect(tauriConfig).toContain('"underWindowBackground"')
  })

  it('defaults new installs to the ink deep-space theme', () => {
    expect(useThemeSource).toContain("return 'ink'")
    expect(useThemeSource).not.toContain("return 'mist'")
  })

  it('softens hover, press, and expand/collapse motion', () => {
    expect(indexCss).toContain('--motion-smooth')
    expect(indexCss).toContain('transition: color var(--motion-fast)')
    expect(indexCss).toContain('transition: flex-basis var(--motion-smooth)')
    expect(indexCss).toContain('transition: opacity var(--motion-fast), transform var(--motion-smooth)')
    expect(indexCss).not.toContain('creationNotchPulse')
  })

  it('keeps dark themes deep, warm, and star-rich without dusty noise', () => {
    expect(indexCss).toContain('--ambient-layer-opacity')
    expect(indexCss).toContain('--ambient-sheen-opacity')
    expect(indexCss).toContain('--ambient-star-twinkle-opacity')
    expect(indexCss).toContain('--deep-space-star-opacity')
    expect(indexCss).toContain('--deep-space-nebula-opacity')
    expect(indexCss).toContain('--deep-space-field-opacity')
    expect(indexCss).toContain('--deep-space-vignette-opacity')
    expect(indexCss).toContain('sparse-star-field')
    expect(indexCss).toContain('deepSpaceDrift')
    expect(indexCss).toContain('--frost-sheen-opacity')
    expect(indexCss).toContain('--frost-grain-opacity')

    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--ambient-star-opacity:\s*0\.035;/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--ambient-star-twinkle-opacity:\s*0\.012;/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--deep-space-star-opacity:\s*0\.34;/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--deep-space-field-opacity:\s*0\.74;/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--deep-space-warm-opacity:\s*0\.7;/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--frost-noise-opacity:\s*0\.035;/)
    expect(indexCss).toMatch(/\[data-theme="graphite"\][\s\S]*--ambient-star-opacity:\s*0\.03;/)
    expect(indexCss).toMatch(/\[data-theme="graphite"\][\s\S]*--ambient-star-twinkle-opacity:\s*0\.01;/)
    expect(indexCss).toMatch(/\[data-theme="graphite"\][\s\S]*--deep-space-star-opacity:\s*0\.28;/)
    expect(indexCss).toMatch(/\[data-theme="graphite"\][\s\S]*--deep-space-field-opacity:\s*0\.64;/)
    expect(indexCss).toMatch(/\[data-theme="graphite"\][\s\S]*--deep-space-warm-opacity:\s*0\.52;/)
    expect(indexCss).toMatch(/\[data-theme="graphite"\][\s\S]*--frost-noise-opacity:\s*0\.03;/)
  })

  it('does not put an independent starfield inside the chat column', () => {
    expect(indexCss).toContain('--chat-star-opacity')
    expect(indexCss).toMatch(/\.studio-chat \{[\s\S]*background:\s*transparent;/)
    expect(indexCss).toMatch(/\.studio-chat \{[\s\S]*backdrop-filter:\s*none;/)
    expect(indexCss).not.toContain('.studio-chat::before')
    expect(indexCss).not.toContain('.studio-chat::after')
  })

  it('keeps chapter review controls in a dedicated workflow bar, not the title actions', () => {
    expect(chapterWorkspace).toContain('chapter-workspace-reviewbar')
    expect(chapterWorkspace).toContain('chapter-workspace-review-actions')
    expect(chapterWorkspace.indexOf('chapter-workspace-reviewbar')).toBeGreaterThan(chapterWorkspace.indexOf('chapter-workspace-head'))
    expect(chapterWorkspace.indexOf('chapter-workspace-reviewbar')).toBeLessThan(chapterWorkspace.indexOf('chapter-workspace-editor'))
    expect(cssBlock('.chapter-workspace')).toContain('grid-template-rows: auto auto minmax(0, 1fr) auto;')
    expect(indexCss).toMatch(/\.chapter-workspace-reviewbar \{[\s\S]*backdrop-filter:/)
    expect(indexCss).toMatch(/\.chapter-workspace-review-actions \{[\s\S]*justify-content:\s*flex-end;/)
  })

  it('keeps lore and characters visible in the right workspace tabs', () => {
    expect(workspaceTabs).toContain("id: 'lore'")
    expect(workspaceTabs).toContain('workspace.lore')
    expect(locales).toContain("'workspace.lore': '设定'")
    expect(locales).toContain("'workspace.lore': 'Lore'")
  })

  it('restores inline chapter annotations and review feed in the studio chapter workspace', () => {
    expect(chapterWorkspace).toContain('useEditorSelection')
    expect(chapterWorkspace).toContain('AnnotationPopover')
    expect(chapterWorkspace).toContain('CommentFeed')
    expect(chapterWorkspace).toContain('/annotations')
    expect(chapterWorkspace).toContain('/send-annotations')
    expect(chapterWorkspace).toContain('/author-chat/${bookId}/send')
    expect(chapterWorkspace).toContain('chapter-workspace-reader')
    expect(chapterWorkspace).toContain('chapter-workspace-inspector')
    expect(chapterWorkspace).toContain("rootSelector: '.chapter-workspace-preview'")
    expect(indexCss).toMatch(/\.chapter-workspace-reader \{[\s\S]*position:\s*relative;/)
    expect(indexCss).toMatch(/\.chapter-workspace-inspector \{[\s\S]*backdrop-filter:/)
    expect(indexCss).toMatch(/\.annotation-popover \{[\s\S]*backdrop-filter:/)
    expect(useEditorSelection).toContain("event.target.closest?.('.annotation-popover')")
  })

  it('covers the entire studio shell with a deep-space mesh, not just the chat center', () => {
    expect(indexCss).toContain('--deep-space-mesh-opacity')
    expect(indexCss).toContain('--deep-space-core-opacity')
    expect(indexCss).toContain('--deep-space-bottom-glow-opacity')
    expect(indexCss).toContain('--deep-space-shell-star-opacity')
    expect(indexCss).toContain('--deep-space-cloud-opacity')
    expect(indexCss).toContain('--deep-space-haze-opacity')
    expect(indexCss).toMatch(/\.studio-shell \{[\s\S]*deep-space-base/)
    expect(indexCss).toMatch(/\.studio-shell::before \{[\s\S]*deep-space-mesh/)
    expect(indexCss).toMatch(/\.studio-shell::after \{[\s\S]*deep-space-stars/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--deep-space-mesh-opacity:\s*0\.46;/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--deep-space-cloud-opacity:\s*0\.5;/)
    expect(indexCss).toMatch(/\[data-theme="graphite"\][\s\S]*--deep-space-mesh-opacity:\s*0\.4;/)
    expect(indexCss).toMatch(/\.studio-library \{[\s\S]*background:[\s\S]*color-mix\(in oklch, var\(--glass-panel\) 12%, transparent\);/)
    expect(indexCss).toMatch(/\.studio-titlebar \{[\s\S]*background:\s*color-mix\(in oklch, var\(--glass-panel\) 18%, transparent\);/)
    expect(indexCss).toMatch(/\.workspace-pane \{[\s\S]*background:[\s\S]*color-mix\(in oklch, var\(--glass-panel\) 14%, transparent\);/)
    expect(indexCss).toMatch(/\.workspace-tab-panel \{[\s\S]*background:\s*transparent;/)
    expect(indexCss).toMatch(/\.chapter-workspace \{[\s\S]*background:\s*transparent;/)
    expect(indexCss).toMatch(/\.outline-view \{[\s\S]*background:\s*transparent;/)
    expect(indexCss).toMatch(/\.plot-graph-view \{[\s\S]*background:\s*transparent;/)
    expect(indexCss).toMatch(/\.game-script-workspace \{[\s\S]*background:\s*transparent;/)
  })

  it('mounts the per-theme atmosphere backdrop in the studio shell', () => {
    expect(studioShell).toContain('AtmosphereBackdrop')
    expect(studioShell).not.toContain('DeepSpaceBackdrop')
  })

  it('atmosphere backdrop self-corrects the transparent-window first-paint via a re-init', () => {
    // On the Tauri transparent WKWebView the first WebGL composite can come up
    // transparent; the component bumps a nonce after mount to re-init once the
    // window has settled (what a manual theme switch does by hand).
    expect(atmosphereBackdrop).toContain('reinitNonce')
    expect(atmosphereBackdrop).toMatch(/\[resolvedTheme, reinitNonce\]/)
  })

  it('keeps the retained deep-space backdrop module as a continuous WebGL shader', () => {
    expect(deepSpaceBackdrop).toContain('deep-space-backdrop')
    expect(deepSpaceBackdrop).toContain('deep-space-backdrop__canvas')
    expect(deepSpaceBackdrop).toContain('requestAnimationFrame')
    expect(deepSpaceBackdrop).toContain('VERTEX_SHADER')
    expect(deepSpaceBackdrop).toContain('DEEP_SPACE_FRAGMENT_SHADER')
    expect(deepSpaceBackdrop).toContain('gl.TRIANGLE_STRIP')
    expect(deepSpaceBackdrop).toContain('u_time')
    expect(deepSpaceBackdrop).toContain('u_res')
    expect(deepSpaceBackdrop).toContain('hash2')
    expect(deepSpaceBackdrop).toContain('fbm')
    expect(deepSpaceBackdrop).toContain('starLayer')
    expect(deepSpaceBackdrop).toContain('nebula')
    expect(deepSpaceBackdrop).not.toContain('TEXTURE_SLICE_COUNT')
    expect(deepSpaceBackdrop).not.toContain('drawTexturedNebula')
    expect(deepSpaceBackdrop).not.toContain('deepSpaceReferenceUrl')
    expect(indexCss).toContain('--deep-space-canvas-opacity')
    expect(indexCss).toContain('--deep-space-warm-opacity')
    expect(indexCss).toMatch(/\.deep-space-backdrop \{[\s\S]*inset:\s*0;/)
    expect(indexCss).not.toContain('url("./assets/deep-space-reference.png")')
    expect(indexCss).toMatch(/\.deep-space-backdrop__canvas \{[\s\S]*width:\s*100%;[\s\S]*height:\s*100%;/)
  })

  it('keeps deep-space motion GPU-bound with a DPR cap and reduced-motion stop path', () => {
    expect(deepSpaceBackdrop).toContain('DPR_CAP = 2')
    expect(deepSpaceBackdrop).toContain('devicePixelRatio')
    expect(deepSpaceBackdrop).toContain('Math.min')
    expect(deepSpaceBackdrop).toContain('matchMedia')
    expect(deepSpaceBackdrop).toContain('prefers-reduced-motion')
    expect(deepSpaceBackdrop).toContain('drawScene(0)')
    expect(deepSpaceBackdrop).toContain('requestAnimationFrame(frame)')
    expect(deepSpaceBackdrop).not.toContain("canvas.getContext('2d')")
    expect(deepSpaceBackdrop).not.toContain('textureCache')
    expect(deepSpaceBackdrop).not.toContain('drawImage(')
    expect(deepSpaceBackdrop).not.toContain('sliceCount = 46')
    expect(deepSpaceBackdrop).not.toContain('NEBULA_PARTICLE_COUNT = 96')
    expect(deepSpaceBackdrop).not.toContain('FILAMENT_COUNT = 9')
    expect(deepSpaceBackdrop).not.toContain('ctx.filter =')
    expect(deepSpaceBackdrop).not.toContain('reducedMotion?.matches) return')
  })

  it('keeps dark-space motion visible with dense stars and blue-warm nebula, not dust specks', () => {
    expect(deepSpaceBackdrop).toContain('STAR_GRID_DENSE = 190.0')
    expect(deepSpaceBackdrop).toContain('STAR_GRID_FINE = 310.0')
    expect(deepSpaceBackdrop).toContain('warmCloud')
    expect(deepSpaceBackdrop).toContain('blueCloud')
    expect(deepSpaceBackdrop).toContain('vec3(0.74, 0.29, 0.18)')
    expect(deepSpaceBackdrop).toContain('vec3(0.16, 0.31, 0.50)')
  })

  it('keeps deep-space motion slow enough to avoid fast fog drift', () => {
    expect(deepSpaceBackdrop).toContain('NEBULA_FLOW_GAIN = 1.18')
    expect(deepSpaceBackdrop).toContain('STAR_TWINKLE_GAIN = 0.32')
    expect(deepSpaceBackdrop).toContain('PARALLAX_DRIFT = 0.07')
    expect(deepSpaceBackdrop).toContain('motionTime = u_time * NEBULA_FLOW_GAIN')
    expect(deepSpaceBackdrop).toContain('flowWarp')
    expect(deepSpaceBackdrop).toContain('starUv')
    expect(deepSpaceBackdrop).not.toContain('time * 0.011')
    expect(deepSpaceBackdrop).not.toContain('time * 0.018, -time * 0.012')
  })

  it('keeps the creation notch compact when the current flow label is short', () => {
    expect(indexCss).toMatch(/\.creation-notch-shell \{[\s\S]*width:\s*fit-content;/)
    expect(indexCss).toMatch(/\.creation-notch \{[\s\S]*top:\s*0;/)
    expect(indexCss).toMatch(/\.creation-notch \{[\s\S]*left:\s*50%;/)
    expect(indexCss).toMatch(/\.creation-notch \{[\s\S]*transform:\s*translateX\(-50%\);/)
    expect(indexCss).toMatch(/\.creation-notch-shell \{[\s\S]*grid-template-columns:\s*13px auto 13px;/)
    expect(indexCss).toMatch(/\.creation-notch-shell \{[\s\S]*padding:\s*4px 8px 7px;/)
    expect(indexCss).toMatch(/\.creation-notch-shell \{[\s\S]*min-width:\s*104px;/)
    expect(indexCss).toMatch(/\.creation-notch-pull-handle \{[\s\S]*width:\s*13px;/)
    expect(indexCss).toMatch(/\.creation-notch-progress-track \{[\s\S]*left:\s*12px;[\s\S]*right:\s*12px;/)
    expect(indexCss).toContain('.creation-notch-balance-spacer')
    expect(indexCss).toContain('.creation-notch-progress-track')
    expect(indexCss).toContain('.creation-notch-progress-fill')
    expect(indexCss).toMatch(/\.creation-notch-panel \{[\s\S]*width:\s*min\(536px/)
    expect(indexCss).not.toMatch(/\.creation-notch-shell \{[\s\S]*width:\s*min\(292px/)
    expect(indexCss).not.toContain('.creation-notch-panel-head')
  })

  it('floats the creative flow panel over chat instead of taking layout height', () => {
    expect(indexCss).toMatch(/\.creation-notch \{[\s\S]*position:\s*absolute;/)
    expect(indexCss).toMatch(/\.creation-notch \{[\s\S]*pointer-events:\s*none;/)
    expect(indexCss).toMatch(/\.creation-notch-shell \{[\s\S]*pointer-events:\s*auto;/)
    expect(indexCss).toMatch(/\.creation-notch-panel \{[\s\S]*position:\s*absolute;/)
    expect(indexCss).toMatch(/\.creation-notch-panel \{[\s\S]*top:\s*calc\(100% \+ 6px\);/)
    expect(indexCss).not.toMatch(/\.creation-notch\.expanded \{[\s\S]*max-height:\s*228px;/)
  })

  it('keeps chat content below the floating creation notch without moving on expand', () => {
    expect(indexCss).toMatch(/\.studio-chat \{[\s\S]*overflow:\s*hidden;/)
    expect(indexCss).toContain('.studio-chat > :not(.creation-notch)')
    expect(indexCss).toContain('--creation-notch-clearance: 34px;')
    expect(indexCss).toMatch(/\.author-chat-scroll \{[\s\S]*padding:\s*calc\(var\(--creation-notch-clearance\) \+ 14px\) 0 20px;/)
    expect(indexCss).toMatch(/\.author-chat-header \{[\s\S]*position:\s*absolute;/)
    expect(indexCss).toMatch(/\.author-chat-header \{[\s\S]*height:\s*0;/)
    expect(indexCss).toMatch(/\.author-chat-title \{[\s\S]*display:\s*none;/)
  })

  it('lets settings scroll inside the fixed chat surface', () => {
    expect(indexCss).toMatch(/\.settings-panel \{[\s\S]*height:\s*100%;/)
    expect(indexCss).toMatch(/\.settings-panel \{[\s\S]*overflow-y:\s*auto;/)
    expect(indexCss).toMatch(/\.settings-panel-inner \{[\s\S]*max-width:\s*680px;/)
  })

  it('keeps the settings title text-only without a decorative icon', () => {
    expect(settingsPanel).toContain('className="settings-panel-title"')
    const titleBlock = settingsPanel.match(/<h2 className="settings-panel-title">[\s\S]*?<\/h2>/)?.[0] || ''
    expect(titleBlock).not.toContain('<Globe')
  })

  it('keeps messages and composer on one centered chat axis', () => {
    expect(indexCss).toContain('--chat-content-width: min(880px, calc(100% - 48px));')
    expect(indexCss).toContain('.author-chat-scroll')
    expect(indexCss).toMatch(/\.chat-message-row \{[\s\S]*width:\s*var\(--chat-content-width\);[\s\S]*margin-inline:\s*auto;/)
    expect(indexCss).toMatch(/\.chat-composer \{[\s\S]*width:\s*var\(--chat-content-width\);/)
    expect(indexCss).toMatch(/\.user-message-stack \{[\s\S]*width:\s*min\(640px, 72%\);/)
    expect(indexCss).toContain('.assistant-segment-stack')
  })

  it('uses frosted glass surfaces without heavy colored glow on chat and composer', () => {
    const userMessageBubbleCss = cssBlock('.user-message-bubble')

    expect(indexCss).toContain('--chat-frost-surface')
    expect(indexCss).toContain('--chat-frost-border')
    expect(indexCss).toContain('--chat-composer-surface')
    expect(indexCss).toContain('--chat-tool-menu-surface')
    expect(indexCss).toContain('--chat-tool-item-surface')
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--chat-composer-surface:\s*color-mix\(in oklch, var\(--bg-elevated\) 52%, transparent\);/)
    expect(indexCss).toMatch(/\[data-theme="ink"\], \[data-theme="dark"\][\s\S]*--chat-tool-menu-surface:\s*color-mix\(in oklch, var\(--bg-elevated\) 82%, transparent\);/)
    expect(indexCss).toMatch(/\.chat-composer \{[\s\S]*background:[\s\S]*var\(--chat-composer-surface\);/)
    expect(indexCss).toMatch(/\.chat-composer \{[\s\S]*backdrop-filter:\s*blur\(38px\) saturate\(1\.24\);/)
    expect(indexCss).toMatch(/\.chat-tool-menu \{[\s\S]*background:[\s\S]*var\(--chat-tool-menu-surface\);/)
    expect(indexCss).toMatch(/\.chat-tool-menu \{[\s\S]*backdrop-filter:\s*blur\(42px\) saturate\(1\.32\);/)
    expect(indexCss).toMatch(/\.chat-tool-menu-item,[\s\S]*\.chat-mode-option \{[\s\S]*background:\s*var\(--chat-tool-item-surface\);/)
    expect(indexCss).toMatch(/\.assistant-message-bubble,[\s\S]*\.streaming-content-bubble \{[\s\S]*var\(--chat-frost-surface\);/)
    expect(indexCss).toMatch(/\.user-message-bubble \{[\s\S]*background:[\s\S]*var\(--chat-frost-surface\);/)
    expect(indexCss).toMatch(/\.user-message-bubble \{[\s\S]*box-shadow:[\s\S]*0 8px 28px oklch\(0% 0 0 \/ 0\.045\)/)
    expect(userMessageBubbleCss).not.toContain('var(--accent)')
  })

  it('removes stale waiting copy and roman-number presentation debt', () => {
    expect(authorChatPanel).not.toContain('idleWaiting')
    expect(authorChatPanel).not.toContain('等待模型响应中')
    expect(locales).not.toContain('authorChat.idleWaiting')
    expect(locales).not.toContain('thinking + 长上下文')
    expect(existsSync(romanUtilUrl)).toBe(false)
    expect([outlineView, sidebar, chapterWorkbench, plotGraphView].join('\n')).not.toContain('toRoman')
  })

  it('keeps chat and outline text readable at studio scale', () => {
    expect(designTokens).toContain('--fs-body: 14px;')
    expect(designTokens).toContain('--fs-small: 12px;')
    expect(designTokens).toContain('--fs-label: 10px;')
    expect(indexCss).toMatch(/\.chapter-body \.chapter-title \{[\s\S]*font-size:\s*15px;/)
    expect(indexCss).toMatch(/\.chapter-body \.chapter-summary \{[\s\S]*font-size:\s*var\(--fs-small\);/)
    expect(indexCss).toMatch(/\.tree-item \{[\s\S]*font-size:\s*13\.5px;[\s\S]*line-height:\s*1\.5;/)
    expect(indexCss).toMatch(/\.assistant-message-bubble,[\s\S]*\.streaming-content-bubble \{[\s\S]*font-size:\s*14px;/)
    expect(indexCss).toMatch(/\.user-message-bubble \{[\s\S]*font-size:\s*14px;/)
    expect(indexCss).toMatch(/\.chat-composer textarea \{[\s\S]*font-size:\s*14px;/)
  })

  it('makes sidebar tree rows accessible keyboard targets for chapter opening', () => {
    expect(sidebar).toContain('role="treeitem"')
    expect(sidebar).toContain('tabIndex={0}')
    expect(sidebar).toContain('aria-selected={selectedId === node.id}')
    expect(sidebar).toContain('aria-expanded={hasChildren ? open : undefined}')
    expect(sidebar).toContain("event.key !== 'Enter'")
    expect(sidebar).toContain("event.key !== ' '")
  })

  it('animates chat messages and live streaming text without changing layout', () => {
    expect(indexCss).toContain('messageLiftIn')
    expect(indexCss).toContain('.chat-message-row')
    expect(indexCss).toContain('.chat-message-enter')
    expect(indexCss).toContain('.streaming-content-bubble')
    expect(indexCss).toContain('.typewriter-caret')
    expect(indexCss).toContain('.tool-activity-group')
    expect(indexCss).toContain('.tool-activity-summary')
    expect(indexCss).toContain('.tool-activity-list')
  })

  it('presents the creative flow as a modern creation notch preview', () => {
    expect(previewHtml).toContain('Creation Notch')
    expect(previewHtml).toContain('notch-shell')
    expect(previewHtml).toContain('notch-timeline')
    expect(previewHtml).toContain('pull-handle')
    expect(previewHtml).not.toContain('Chat 内折叠状态卡')
  })
})
