from typing import Any, Dict, Optional
import json
from src.core.llm_client import BaseLLMClient

class MockLLMClient(BaseLLMClient):
    """
    Mock LLM Client for offline unit testing.
    Does not connect to any actual API but returns hardcoded or configurable responses.
    """

    def __init__(self, mock_responses: Optional[Dict[str, Any]] = None, **kwargs):
        """
        Initialize Mock LLM Client.

        Args:
            mock_responses: Dictionary mapping expected prompt keywords or types to returning responses.
                            E.g. {"json_test": {"key": "value"}, "text_test": "Generates mock text"}
        """
        super().__init__(model_name="mock-model", api_key="sk-mock", **kwargs)
        self.mock_responses = mock_responses or {}
        self.call_history = []

    async def _generate_text(self, system_prompt: str, user_prompt: str, **kwargs) -> str:
        """Return a mock text response."""
        self.call_history.append({
            "type": "text",
            "system_prompt": system_prompt,
            "user_prompt": user_prompt,
            "kwargs": kwargs
        })

        # Match against predefined mock responses if available
        for key, response in self.mock_responses.items():
            if key in system_prompt or key in user_prompt:
                if isinstance(response, str):
                    return response
                return json.dumps(response)

        return "This is a mock text generated by the MockLLMClient."

    async def _generate_json(self, system_prompt: str, user_prompt: str, **kwargs) -> Dict[str, Any]:
        """Return a mock JSON response."""
        self.call_history.append({
            "type": "json",
            "system_prompt": system_prompt,
            "user_prompt": user_prompt,
            "kwargs": kwargs
        })

        # Check for response_format injection testing
        has_response_format = kwargs.get("response_format") is not None
        
        # Match against predefined mock responses if available
        for key, response in self.mock_responses.items():
            if key in system_prompt or key in user_prompt:
                if isinstance(response, dict):
                    # Inject a tracking field if response_format was used
                    if has_response_format:
                        response["_mock_used_format"] = True
                    return response
                return json.loads(response)

        # Default mock standard JSON structure depending on common use-cases
        default_resp = {"status": "success", "mocked": True}
        if has_response_format:
            default_resp["_mock_used_format"] = True
        return default_resp

    async def close(self):
        """Close mock connection (no-op)."""
        pass
